export enum FOLDER_NAMES {
     IMAGE = 'image',
     IMAGES = 'images',
     LICENSE = 'license',
     DRIVER_LICENSE = 'driverLicense',
     INSURANCE = 'insurance',
     PERMITS = 'permits',
     BANNER = 'banner',
     LOGO = 'logo',
     AUDIO = 'audio',
     VIDEO = 'video',
     DOCUMENT = 'document',
     THUMBNAIL = 'thumbnail',
     OTHERS = 'others',
}
